title: Kevin Heavey
description: The personal blog of Kevin Heavey.
url: https://kevinheavey.dev
baseurl: ""
lang: en
timezone: Europe/Dublin
permalink: /:year/:month/:day/:title/
markdown: kramdown
kramdown:
  input: GFM
exclude:
  - README.md
