title: Kevin Heavey
description: Notes on great and terrible things
url: https://heavey.dev
baseurl: ""
lang: en
timezone: Europe/Dublin
permalink: /:year/:month/:day/:title/
markdown: kramdown
kramdown:
  input: GFM
exclude:
  - README.md
